version: '3.0'

services:
  grafana:
    container_name: 'runreveal-runreveal-datasource'
    build:
      context: ./.config
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/runreveal-runreveal-datasource
      - ./provisioning:/etc/grafana/provisioning
