{
 "title": "RunReveal Default Dashboard",
 "description": "A dashboard to get you setup with the RunReveal Grafana Plugin.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "runreveal_source", "label": "Data Source", "query": "runreveal-runreveal-datasource" }
  ]
 },
 "panels": [
  {
   "title": "RunReveal Health - $runreveal_source",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "runreveal_source"
  },
  {
   "title": "Average # of Events/Sec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "SELECT count(*)/(10*60) FROM logs WHERE   ( receivedAt BETWEEN subtractMinutes(now(),10) AND now() )"
    },
    {
     "rawQuery": "SELECT count(*)/(24*60*60) Today FROM logs WHERE   ( receivedAt BETWEEN subtractDays(now(),1) AND now() )"
    }
   ]
  },
  {
   "title": "Amount of Data Ingested this Month",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "select count(*) amount, sum(length(rawLog)) dataSize from runreveal_logs where receivedAt >= toStartOfMonth(now())"
    }
   ]
  },
  {
   "title": "Events Ingested By Source",
   "type": "piechart",
   "description": "Show the number of events that have been ingested over the time period.",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "select sourceType, count(*) count from runreveal_logs\nwhere eventTime between $__fromTime and $__toTime\ngroup by sourceType\n"
    }
   ]
  },
  {
   "title": "RunReveal Logs over 5 minute windows",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 6 },
   "targets": [
    {
     "rawQuery": "SELECT $__timeInterval(receivedAt) as time,  count(*) FROM logs WHERE    ( receivedAt  >= $__fromTime AND receivedAt <= $__toTime ) GROUP BY time ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Cloudtrail Logs - $runreveal_source",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "runreveal_source"
  },
  {
   "title": "AWS Access Key Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "rawQuery": "select $__timeInterval(eventTime) time,\n       userIdentity.accessKeyId || ' - ' || userIdentity.userName accessKeyId\n       , count(*) val from cloudtrail_logs\nwhere eventTime BETWEEN $__fromTime AND $__toTime\nAND userIdentity.accessKeyId <> '' AND userIdentity.userName <> ''\nGROUP BY time, accessKeyId\norder by time"
    }
   ]
  },
  {
   "title": "AWS Secret Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "rawQuery": "select\n    $__timeInterval(eventTime) time,\n-- coalesce(nullIf(userIdentity.userName, ''), userIdentity.sessionContext.sessionIssuer.userName)\nJSONExtractString(requestParameters, 'secretId') secretName,\nCOUNT(*) count\nfrom cloudtrail_logs\nwhere\n    eventTime BETWEEN $__fromTime AND $__toTime\n    AND eventSource = 'secretsmanager.amazonaws.com'\n    and eventName = 'GetSecretValue'\nGROUP BY time, secretName\norder by time\n"
    }
   ]
  },
  {
   "title": "AWS Failed Logins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "rawQuery": "SELECT $__timeInterval(eventTime) time,\nuserIdentity.userName user,\nCount(*) Count\nFROM cloudtrail_logs\nwhere eventType = 'AwsConsoleSignIn' and eventName = 'ConsoleLogin'\n  AND eventTime BETWEEN $__fromTime and $__toTime\nand JSONExtractString(responseElements, 'ConsoleLogin') = 'Failure'\nGROUP bY time, user\norder by time"
    }
   ]
  },
  {
   "title": "AWS Console Logins",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "rawQuery": "SELECT\nJSONExtractString(responseElements, 'ConsoleLogin') loginStatus,\nsrcASCountryCode,\nCount(*) Count\nFROM cloudtrail_logs\nwhere eventType = 'AwsConsoleSignIn' and eventName = 'ConsoleLogin'\n  AND eventTime between $__fromTime AND $__toTime\n  AND srcASCountryCode IS NOT NULL AND srcASCountryCode <> ''\nGROUP bY srcASCountryCode, loginStatus"
    }
   ]
  }
 ]
}